Add patch to fix some guestinstance tests
atom/libchromiumcontent pull request #551
Opened 2018-05-22 21:38 UTC by codebytere

After enabling verbose logging, it appeared that some guestinstance tests were crashing as a result of 
```
[25755:0522/121849.511223:ERROR:sync_point_manager.cc(136)] Client did not release sync token as expected
```
errors. 

This error was also seen [here], and subsequently repaired in chromium with [this] CL.

This PR backports that CL Chromium 66.

/cc @alexeykuzmin @deepak1556

2018-05-22 22:38 UTC, alexeykuzmin commented
`> backport_3743d0f.patch failed to apply` =(

2018-05-23 03:16 UTC, deepak1556 requested changes
https://chromium-review.googlesource.com/c/chromium/src/+/969968 should also be backported.

2018-05-24 12:49 UTC, alexeykuzmin commented
There is no need to backport commit [`3743d0f`](https://chromium.googlesource.com/chromium/src/+/3743d0f5f0614909a354a8df3af879f0eff21c42), it has already been backported to M66 in commit [`4ec34bb`](https://chromium.googlesource.com/chromium/src/+/4ec34bb46504fcfce52bb6644b570cd48157a79f).

2018-05-24 12:49 UTC, alexeykuzmin commented
> https://chromium-review.googlesource.com/c/chromium/src/+/969968 should also be backported.

I'll do it separately.

2018-05-24 12:54 UTC, closed without merging